import React,{useCallback,useMemo,useRef,useEffect} from 'react';
import CytoscapeComponent from 'react-cytoscapejs';
import cytoscape from 'cytoscape';
import type{Core,EventObject,NodeSingular} from 'cytoscape';
import {getGraphStyles} from '../../graph/graphStyles';
import type{GraphNode,GraphData,LayoutData} from '../../graph/graphTypes';
interface Props{graphData:GraphData|null;layoutData?:LayoutData|null;nodeTypeFilters:Record<string,boolean>;edgeTypeFilters:Record<string,boolean>;clusterFilter:number|null;selectedNodeId:string|null;focusToken?:number;onNodeClick:(n:GraphNode|null)=>void;isLoading?:boolean;isAtlasMode?:boolean;}
const GC:React.FC<Props>=({graphData,layoutData,nodeTypeFilters,edgeTypeFilters,clusterFilter,selectedNodeId,focusToken=0,onNodeClick,isLoading,isAtlasMode})=>{
  const cyR=useRef<Core|null>(null);
  const zoomRef=useRef(1);
  const zoomInputRef=useRef<HTMLInputElement|null>(null);
  const fltrd=useMemo(()=>{if(!graphData)return{nodes:[],edges:[]};const nt=Object.entries(nodeTypeFilters).filter(([,v])=>v!==false).map(([k])=>k);const et=Object.entries(edgeTypeFilters).filter(([,v])=>v!==false).map(([k])=>k);const ns=new Set<string>();const nodes=graphData.nodes.filter(n=>{if(!nt.includes(n.type))return false;if(clusterFilter!==null&&n.cluster!==clusterFilter)return false;ns.add(n.id);return true;});const edges=graphData.edges.filter(e=>et.includes(e.type)&&ns.has(e.source)&&ns.has(e.target));return{nodes,edges};},[graphData,nodeTypeFilters,edgeTypeFilters,clusterFilter]);
  const eles=useMemo(()=>{const e:cytoscape.ElementDefinition[]=[];for(const n of fltrd.nodes){const p:{x?:number;y?:number}={};const lp=layoutData?.positions[n.id];if(n.x!==undefined){p.x=n.x;p.y=n.y;}else if(lp){p.x=lp.x;p.y=lp.y;}e.push({group:'nodes',data:{id:n.id,label:n.label,type:n.type,weight:n.weight,cluster:n.cluster},position:p.x!==undefined?{x:p.x,y:p.y}:undefined});}for(const ed of fltrd.edges)e.push({group:'edges',data:{id:ed.id,source:ed.source,target:ed.target,type:ed.type,weight:ed.weight}});return e;},[fltrd,layoutData]);
  const updateZoomControl=useCallback((value:number)=>{if(zoomInputRef.current){zoomInputRef.current.value=Number(value.toFixed(2)).toString();}},[]);
  const handleZoomChange=useCallback((value:number)=>{const cy=cyR.current;if(!cy)return;const next=Math.max(0.1,Math.min(10,Number(value.toFixed(2))));zoomRef.current=next;updateZoomControl(next);cy.zoom(next);cy.center();},[updateZoomControl]);
  const init=useCallback((cy:Core)=>{cyR.current=cy;const syncZoom=()=>{const next=Number(cy.zoom().toFixed(2));zoomRef.current=next;updateZoomControl(next);};zoomRef.current=Number(cy.zoom().toFixed(2));updateZoomControl(zoomRef.current);cy.on('zoom',syncZoom);cy.on('tap','node',(evt:EventObject)=>{const d=(evt.target as NodeSingular).data();onNodeClick(graphData?.nodes.find(n=>n.id===d.id)||null);});cy.on('tap',(evt:EventObject)=>{if(evt.target===cy)onNodeClick(null);});if(eles.length>0&&!layoutData)cy.layout({name:'cose',animate:true,animationDuration:300,fit:true,padding:30}).run();else if(eles.length>0)setTimeout(()=>cy.fit(undefined,50),50);return()=>{cy.off('zoom',syncZoom);};},[graphData,layoutData,onNodeClick,eles.length,updateZoomControl]);
  useEffect(()=>{if(!cyR.current||!selectedNodeId)return;const centerSelectedNode=()=>{const cy=cyR.current;if(!cy)return;const n=cy.getElementById(selectedNodeId);if(n.length===0)return;const renderedPos=n.renderedPosition();const targetZoom=Math.min(2.4,Math.max(1.2,cy.zoom()));cy.stop();cy.animate({center:{x:renderedPos.x,y:renderedPos.y},zoom:targetZoom,duration:450,easing:'ease-out-cubic'});n.select();};const timerId=window.setTimeout(centerSelectedNode,0);const retryId=window.setTimeout(centerSelectedNode,220);return ()=>{window.clearTimeout(timerId);window.clearTimeout(retryId);};},[selectedNodeId,focusToken]);
  if(isLoading)return<div className="graph-loading"><div className="loading-spinner"></div><p>Loading graph...</p></div>;
  if(!graphData||!graphData.nodes.length)return<div className="graph-empty"><p>No graph data loaded.</p></div>;
  return<div className="graph-canvas-container"><CytoscapeComponent elements={eles} style={{width:'100%',height:'100%',position:'absolute',top:0,left:0}} stylesheet={getGraphStyles()} layout={{name:'preset'}} cy={init} zoomingEnabled={true} panningEnabled={true} minZoom={0.1} maxZoom={10} wheelSensitivity={0.3}/>{isAtlasMode&&<div className="atlas-zoom-bar"><span className="atlas-zoom-label">Zoom</span><button className="atlas-zoom-btn" onClick={()=>handleZoomChange(Math.max(0.1,zoomRef.current-0.2))} aria-label="Zoom out">−</button><input ref={zoomInputRef} className="atlas-zoom-slider" type="range" min="0.1" max="10" step="0.1" defaultValue={1} onChange={(e)=>handleZoomChange(Number(e.target.value))}/><button className="atlas-zoom-btn" onClick={()=>handleZoomChange(Math.min(10,zoomRef.current+0.2))} aria-label="Zoom in">+</button><button className="atlas-zoom-reset" onClick={()=>handleZoomChange(1)}>Reset</button></div>}<div className="graph-info">{fltrd.nodes.length} nodes / {fltrd.edges.length} edges</div></div>;
};
export default GC;
